import {Schema, model} from 'mongoose';

export interface User{ 
    id:string;
    name:string;
    email: string;
    password:string;
    address:string;
    isAdmin:boolean;
}

export const UserSchema = new Schema<User>(
    {
        name: {type: String, required:true},
        email: {type:String , required: true,unique:true},
        password: {type:String , required: true},
        address: {type:String , required: true},
        isAdmin: {type:Boolean , required: true},
    
    },{
        toJSON:{
            // virtuals wiil be generated by the database
            // so we want our userid to be used by mongoose ie _id
            // we need to allow virtuals to true
            virtuals:true

        },
        toObject:{
                // when you get value from db and you want to work in code with it
                virtuals:true

        },
        timestamps:true
    }
);

export const UserModel= model<User>('user', UserSchema)